name: Hello
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Hello, world"
        echo 2
        git log -1
        tree -a .
      - uses: actions/checkout@v4
