name: Hello
on: [push, pull_request]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run script
        run: |
          echo "Hello, world"
          echo 2
          git log -1
          tree -a .
      - name: Checkout repository
        uses: actions/checkout@v4
